package autoinit

type MDCName string

const MDCBanner MDCName = "MDCBanner"
const MDCCheckbox MDCName = "MDCCheckbox"
const MDCChip MDCName = "MDCChip"
const MDCChipSet MDCName = "MDCChipSet"
const MDCCircularProgress MDCName = "MDCCircularProgress"
const MDCDataTable MDCName = "MDCDataTable"
const MDCDialog MDCName = "MDCDialog"
const MDCDrawer MDCName = "MDCDrawer"
const MDCFloatingLabel MDCName = "MDCFloatingLabel"
const MDCFormField MDCName = "MDCFormField"
const MDCIconButtonToggle MDCName = "MDCIconButtonToggle"
const MDCLineRipple MDCName = "MDCLineRipple"
const MDCLinearProgress MDCName = "MDCLinearProgress"
const MDCList MDCName = "MDCList"
const MDCMenu MDCName = "MDCMenu"
const MDCMenuSurface MDCName = "MDCMenuSurface"
const MDCNotchedOutline MDCName = "MDCNotchedOutline"
const MDCRadio MDCName = "MDCRadio"
const MDCRipple MDCName = "MDCRipple"
const MDCSegmentedButton MDCName = "MDCSegmentedButton"
const MDCSelect MDCName = "MDCSelect"
const MDCSlider MDCName = "MDCSlider"
const MDCSnackbar MDCName = "MDCSnackbar"
const MDCSwitch MDCName = "MDCSwitch"
const MDCTabBar MDCName = "MDCTabBar"
const MDCTextField MDCName = "MDCTextField"
const MDCTooltip MDCName = "MDCTooltip"
const MDCTopAppBar MDCName = "MDCTopAppBar"
